// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

/**
 * Protobuf type {@code FlightDestDepDTO}
 */
public final class FlightDestDepDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FlightDestDepDTO)
    FlightDestDepDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlightDestDepDTO.newBuilder() to construct.
  private FlightDestDepDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlightDestDepDTO() {
    destination_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FlightDestDepDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FlightDestDepDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            destination_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (departure_ != null) {
              subBuilder = departure_.toBuilder();
            }
            departure_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(departure_);
              departure_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return generatedcode.TravelProto.internal_static_FlightDestDepDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return generatedcode.TravelProto.internal_static_FlightDestDepDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            generatedcode.FlightDestDepDTO.class, generatedcode.FlightDestDepDTO.Builder.class);
  }

  public static final int DESTINATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object destination_;
  /**
   * <code>string destination = 1;</code>
   * @return The destination.
   */
  @java.lang.Override
  public java.lang.String getDestination() {
    java.lang.Object ref = destination_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destination_ = s;
      return s;
    }
  }
  /**
   * <code>string destination = 1;</code>
   * @return The bytes for destination.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationBytes() {
    java.lang.Object ref = destination_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp departure_;
  /**
   * <code>.google.protobuf.Timestamp departure = 2;</code>
   * @return Whether the departure field is set.
   */
  @java.lang.Override
  public boolean hasDeparture() {
    return departure_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp departure = 2;</code>
   * @return The departure.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeparture() {
    return departure_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : departure_;
  }
  /**
   * <code>.google.protobuf.Timestamp departure = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDepartureOrBuilder() {
    return getDeparture();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destination_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, destination_);
    }
    if (departure_ != null) {
      output.writeMessage(2, getDeparture());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destination_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, destination_);
    }
    if (departure_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDeparture());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof generatedcode.FlightDestDepDTO)) {
      return super.equals(obj);
    }
    generatedcode.FlightDestDepDTO other = (generatedcode.FlightDestDepDTO) obj;

    if (!getDestination()
        .equals(other.getDestination())) return false;
    if (hasDeparture() != other.hasDeparture()) return false;
    if (hasDeparture()) {
      if (!getDeparture()
          .equals(other.getDeparture())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getDestination().hashCode();
    if (hasDeparture()) {
      hash = (37 * hash) + DEPARTURE_FIELD_NUMBER;
      hash = (53 * hash) + getDeparture().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static generatedcode.FlightDestDepDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.FlightDestDepDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static generatedcode.FlightDestDepDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.FlightDestDepDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(generatedcode.FlightDestDepDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FlightDestDepDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FlightDestDepDTO)
      generatedcode.FlightDestDepDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedcode.TravelProto.internal_static_FlightDestDepDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedcode.TravelProto.internal_static_FlightDestDepDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedcode.FlightDestDepDTO.class, generatedcode.FlightDestDepDTO.Builder.class);
    }

    // Construct using generatedcode.FlightDestDepDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      destination_ = "";

      if (departureBuilder_ == null) {
        departure_ = null;
      } else {
        departure_ = null;
        departureBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return generatedcode.TravelProto.internal_static_FlightDestDepDTO_descriptor;
    }

    @java.lang.Override
    public generatedcode.FlightDestDepDTO getDefaultInstanceForType() {
      return generatedcode.FlightDestDepDTO.getDefaultInstance();
    }

    @java.lang.Override
    public generatedcode.FlightDestDepDTO build() {
      generatedcode.FlightDestDepDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public generatedcode.FlightDestDepDTO buildPartial() {
      generatedcode.FlightDestDepDTO result = new generatedcode.FlightDestDepDTO(this);
      result.destination_ = destination_;
      if (departureBuilder_ == null) {
        result.departure_ = departure_;
      } else {
        result.departure_ = departureBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof generatedcode.FlightDestDepDTO) {
        return mergeFrom((generatedcode.FlightDestDepDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(generatedcode.FlightDestDepDTO other) {
      if (other == generatedcode.FlightDestDepDTO.getDefaultInstance()) return this;
      if (!other.getDestination().isEmpty()) {
        destination_ = other.destination_;
        onChanged();
      }
      if (other.hasDeparture()) {
        mergeDeparture(other.getDeparture());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      generatedcode.FlightDestDepDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (generatedcode.FlightDestDepDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object destination_ = "";
    /**
     * <code>string destination = 1;</code>
     * @return The destination.
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destination_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination = 1;</code>
     * @return The bytes for destination.
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination = 1;</code>
     * @param value The destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestination(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestination() {
      
      destination_ = getDefaultInstance().getDestination();
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 1;</code>
     * @param value The bytes for destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destination_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp departure_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> departureBuilder_;
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     * @return Whether the departure field is set.
     */
    public boolean hasDeparture() {
      return departureBuilder_ != null || departure_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     * @return The departure.
     */
    public com.google.protobuf.Timestamp getDeparture() {
      if (departureBuilder_ == null) {
        return departure_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : departure_;
      } else {
        return departureBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     */
    public Builder setDeparture(com.google.protobuf.Timestamp value) {
      if (departureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        departure_ = value;
        onChanged();
      } else {
        departureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     */
    public Builder setDeparture(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (departureBuilder_ == null) {
        departure_ = builderForValue.build();
        onChanged();
      } else {
        departureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     */
    public Builder mergeDeparture(com.google.protobuf.Timestamp value) {
      if (departureBuilder_ == null) {
        if (departure_ != null) {
          departure_ =
            com.google.protobuf.Timestamp.newBuilder(departure_).mergeFrom(value).buildPartial();
        } else {
          departure_ = value;
        }
        onChanged();
      } else {
        departureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     */
    public Builder clearDeparture() {
      if (departureBuilder_ == null) {
        departure_ = null;
        onChanged();
      } else {
        departure_ = null;
        departureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDepartureBuilder() {
      
      onChanged();
      return getDepartureFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDepartureOrBuilder() {
      if (departureBuilder_ != null) {
        return departureBuilder_.getMessageOrBuilder();
      } else {
        return departure_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : departure_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDepartureFieldBuilder() {
      if (departureBuilder_ == null) {
        departureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeparture(),
                getParentForChildren(),
                isClean());
        departure_ = null;
      }
      return departureBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FlightDestDepDTO)
  }

  // @@protoc_insertion_point(class_scope:FlightDestDepDTO)
  private static final generatedcode.FlightDestDepDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new generatedcode.FlightDestDepDTO();
  }

  public static generatedcode.FlightDestDepDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlightDestDepDTO>
      PARSER = new com.google.protobuf.AbstractParser<FlightDestDepDTO>() {
    @java.lang.Override
    public FlightDestDepDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FlightDestDepDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FlightDestDepDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FlightDestDepDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public generatedcode.FlightDestDepDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

