// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public interface FlightDestDepDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FlightDestDepDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string destination = 1;</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 1;</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>.google.protobuf.Timestamp departure = 2;</code>
   * @return Whether the departure field is set.
   */
  boolean hasDeparture();
  /**
   * <code>.google.protobuf.Timestamp departure = 2;</code>
   * @return The departure.
   */
  com.google.protobuf.Timestamp getDeparture();
  /**
   * <code>.google.protobuf.Timestamp departure = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDepartureOrBuilder();
}
