// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

/**
 * Protobuf type {@code Flight}
 */
public final class Flight extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Flight)
    FlightOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Flight.newBuilder() to construct.
  private Flight(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Flight() {
    destination_ = "";
    airport_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Flight();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Flight(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            destination_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (departure_ != null) {
              subBuilder = departure_.toBuilder();
            }
            departure_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(departure_);
              departure_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            airport_ = s;
            break;
          }
          case 40: {

            availableSeats_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return generatedcode.TravelProto.internal_static_Flight_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return generatedcode.TravelProto.internal_static_Flight_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            generatedcode.Flight.class, generatedcode.Flight.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int DESTINATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object destination_;
  /**
   * <code>string destination = 2;</code>
   * @return The destination.
   */
  @java.lang.Override
  public java.lang.String getDestination() {
    java.lang.Object ref = destination_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destination_ = s;
      return s;
    }
  }
  /**
   * <code>string destination = 2;</code>
   * @return The bytes for destination.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationBytes() {
    java.lang.Object ref = destination_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp departure_;
  /**
   * <code>.google.protobuf.Timestamp departure = 3;</code>
   * @return Whether the departure field is set.
   */
  @java.lang.Override
  public boolean hasDeparture() {
    return departure_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp departure = 3;</code>
   * @return The departure.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeparture() {
    return departure_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : departure_;
  }
  /**
   * <code>.google.protobuf.Timestamp departure = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDepartureOrBuilder() {
    return getDeparture();
  }

  public static final int AIRPORT_FIELD_NUMBER = 4;
  private volatile java.lang.Object airport_;
  /**
   * <code>string airport = 4;</code>
   * @return The airport.
   */
  @java.lang.Override
  public java.lang.String getAirport() {
    java.lang.Object ref = airport_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      airport_ = s;
      return s;
    }
  }
  /**
   * <code>string airport = 4;</code>
   * @return The bytes for airport.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAirportBytes() {
    java.lang.Object ref = airport_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      airport_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLESEATS_FIELD_NUMBER = 5;
  private int availableSeats_;
  /**
   * <code>int32 availableSeats = 5;</code>
   * @return The availableSeats.
   */
  @java.lang.Override
  public int getAvailableSeats() {
    return availableSeats_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destination_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destination_);
    }
    if (departure_ != null) {
      output.writeMessage(3, getDeparture());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(airport_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, airport_);
    }
    if (availableSeats_ != 0) {
      output.writeInt32(5, availableSeats_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destination_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destination_);
    }
    if (departure_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDeparture());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(airport_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, airport_);
    }
    if (availableSeats_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, availableSeats_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof generatedcode.Flight)) {
      return super.equals(obj);
    }
    generatedcode.Flight other = (generatedcode.Flight) obj;

    if (getId()
        != other.getId()) return false;
    if (!getDestination()
        .equals(other.getDestination())) return false;
    if (hasDeparture() != other.hasDeparture()) return false;
    if (hasDeparture()) {
      if (!getDeparture()
          .equals(other.getDeparture())) return false;
    }
    if (!getAirport()
        .equals(other.getAirport())) return false;
    if (getAvailableSeats()
        != other.getAvailableSeats()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getDestination().hashCode();
    if (hasDeparture()) {
      hash = (37 * hash) + DEPARTURE_FIELD_NUMBER;
      hash = (53 * hash) + getDeparture().hashCode();
    }
    hash = (37 * hash) + AIRPORT_FIELD_NUMBER;
    hash = (53 * hash) + getAirport().hashCode();
    hash = (37 * hash) + AVAILABLESEATS_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableSeats();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static generatedcode.Flight parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.Flight parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.Flight parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.Flight parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.Flight parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.Flight parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.Flight parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.Flight parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.Flight parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static generatedcode.Flight parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.Flight parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.Flight parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(generatedcode.Flight prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Flight}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Flight)
      generatedcode.FlightOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedcode.TravelProto.internal_static_Flight_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedcode.TravelProto.internal_static_Flight_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedcode.Flight.class, generatedcode.Flight.Builder.class);
    }

    // Construct using generatedcode.Flight.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      destination_ = "";

      if (departureBuilder_ == null) {
        departure_ = null;
      } else {
        departure_ = null;
        departureBuilder_ = null;
      }
      airport_ = "";

      availableSeats_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return generatedcode.TravelProto.internal_static_Flight_descriptor;
    }

    @java.lang.Override
    public generatedcode.Flight getDefaultInstanceForType() {
      return generatedcode.Flight.getDefaultInstance();
    }

    @java.lang.Override
    public generatedcode.Flight build() {
      generatedcode.Flight result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public generatedcode.Flight buildPartial() {
      generatedcode.Flight result = new generatedcode.Flight(this);
      result.id_ = id_;
      result.destination_ = destination_;
      if (departureBuilder_ == null) {
        result.departure_ = departure_;
      } else {
        result.departure_ = departureBuilder_.build();
      }
      result.airport_ = airport_;
      result.availableSeats_ = availableSeats_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof generatedcode.Flight) {
        return mergeFrom((generatedcode.Flight)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(generatedcode.Flight other) {
      if (other == generatedcode.Flight.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getDestination().isEmpty()) {
        destination_ = other.destination_;
        onChanged();
      }
      if (other.hasDeparture()) {
        mergeDeparture(other.getDeparture());
      }
      if (!other.getAirport().isEmpty()) {
        airport_ = other.airport_;
        onChanged();
      }
      if (other.getAvailableSeats() != 0) {
        setAvailableSeats(other.getAvailableSeats());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      generatedcode.Flight parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (generatedcode.Flight) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object destination_ = "";
    /**
     * <code>string destination = 2;</code>
     * @return The destination.
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destination_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination = 2;</code>
     * @return The bytes for destination.
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination = 2;</code>
     * @param value The destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestination(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestination() {
      
      destination_ = getDefaultInstance().getDestination();
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 2;</code>
     * @param value The bytes for destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destination_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp departure_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> departureBuilder_;
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     * @return Whether the departure field is set.
     */
    public boolean hasDeparture() {
      return departureBuilder_ != null || departure_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     * @return The departure.
     */
    public com.google.protobuf.Timestamp getDeparture() {
      if (departureBuilder_ == null) {
        return departure_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : departure_;
      } else {
        return departureBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     */
    public Builder setDeparture(com.google.protobuf.Timestamp value) {
      if (departureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        departure_ = value;
        onChanged();
      } else {
        departureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     */
    public Builder setDeparture(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (departureBuilder_ == null) {
        departure_ = builderForValue.build();
        onChanged();
      } else {
        departureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     */
    public Builder mergeDeparture(com.google.protobuf.Timestamp value) {
      if (departureBuilder_ == null) {
        if (departure_ != null) {
          departure_ =
            com.google.protobuf.Timestamp.newBuilder(departure_).mergeFrom(value).buildPartial();
        } else {
          departure_ = value;
        }
        onChanged();
      } else {
        departureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     */
    public Builder clearDeparture() {
      if (departureBuilder_ == null) {
        departure_ = null;
        onChanged();
      } else {
        departure_ = null;
        departureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDepartureBuilder() {
      
      onChanged();
      return getDepartureFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDepartureOrBuilder() {
      if (departureBuilder_ != null) {
        return departureBuilder_.getMessageOrBuilder();
      } else {
        return departure_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : departure_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp departure = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDepartureFieldBuilder() {
      if (departureBuilder_ == null) {
        departureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeparture(),
                getParentForChildren(),
                isClean());
        departure_ = null;
      }
      return departureBuilder_;
    }

    private java.lang.Object airport_ = "";
    /**
     * <code>string airport = 4;</code>
     * @return The airport.
     */
    public java.lang.String getAirport() {
      java.lang.Object ref = airport_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        airport_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string airport = 4;</code>
     * @return The bytes for airport.
     */
    public com.google.protobuf.ByteString
        getAirportBytes() {
      java.lang.Object ref = airport_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        airport_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string airport = 4;</code>
     * @param value The airport to set.
     * @return This builder for chaining.
     */
    public Builder setAirport(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      airport_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string airport = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAirport() {
      
      airport_ = getDefaultInstance().getAirport();
      onChanged();
      return this;
    }
    /**
     * <code>string airport = 4;</code>
     * @param value The bytes for airport to set.
     * @return This builder for chaining.
     */
    public Builder setAirportBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      airport_ = value;
      onChanged();
      return this;
    }

    private int availableSeats_ ;
    /**
     * <code>int32 availableSeats = 5;</code>
     * @return The availableSeats.
     */
    @java.lang.Override
    public int getAvailableSeats() {
      return availableSeats_;
    }
    /**
     * <code>int32 availableSeats = 5;</code>
     * @param value The availableSeats to set.
     * @return This builder for chaining.
     */
    public Builder setAvailableSeats(int value) {
      
      availableSeats_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 availableSeats = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailableSeats() {
      
      availableSeats_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Flight)
  }

  // @@protoc_insertion_point(class_scope:Flight)
  private static final generatedcode.Flight DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new generatedcode.Flight();
  }

  public static generatedcode.Flight getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Flight>
      PARSER = new com.google.protobuf.AbstractParser<Flight>() {
    @java.lang.Override
    public Flight parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Flight(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Flight> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Flight> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public generatedcode.Flight getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

