// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public interface FlightOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Flight)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string destination = 2;</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 2;</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>.google.protobuf.Timestamp departure = 3;</code>
   * @return Whether the departure field is set.
   */
  boolean hasDeparture();
  /**
   * <code>.google.protobuf.Timestamp departure = 3;</code>
   * @return The departure.
   */
  com.google.protobuf.Timestamp getDeparture();
  /**
   * <code>.google.protobuf.Timestamp departure = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDepartureOrBuilder();

  /**
   * <code>string airport = 4;</code>
   * @return The airport.
   */
  java.lang.String getAirport();
  /**
   * <code>string airport = 4;</code>
   * @return The bytes for airport.
   */
  com.google.protobuf.ByteString
      getAirportBytes();

  /**
   * <code>int32 availableSeats = 5;</code>
   * @return The availableSeats.
   */
  int getAvailableSeats();
}
