// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public interface TicketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ticket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string customerName = 2;</code>
   * @return The customerName.
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customerName = 2;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string touristName = 3;</code>
   * @return The touristName.
   */
  java.lang.String getTouristName();
  /**
   * <code>string touristName = 3;</code>
   * @return The bytes for touristName.
   */
  com.google.protobuf.ByteString
      getTouristNameBytes();

  /**
   * <code>string customerAddress = 4;</code>
   * @return The customerAddress.
   */
  java.lang.String getCustomerAddress();
  /**
   * <code>string customerAddress = 4;</code>
   * @return The bytes for customerAddress.
   */
  com.google.protobuf.ByteString
      getCustomerAddressBytes();

  /**
   * <code>int32 seats = 5;</code>
   * @return The seats.
   */
  int getSeats();

  /**
   * <code>.Flight flight = 6;</code>
   * @return Whether the flight field is set.
   */
  boolean hasFlight();
  /**
   * <code>.Flight flight = 6;</code>
   * @return The flight.
   */
  generatedcode.Flight getFlight();
  /**
   * <code>.Flight flight = 6;</code>
   */
  generatedcode.FlightOrBuilder getFlightOrBuilder();
}
