// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

/**
 * Protobuf type {@code Ticket}
 */
public final class Ticket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ticket)
    TicketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ticket.newBuilder() to construct.
  private Ticket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ticket() {
    customerName_ = "";
    touristName_ = "";
    customerAddress_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ticket();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Ticket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            customerName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            touristName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            customerAddress_ = s;
            break;
          }
          case 40: {

            seats_ = input.readInt32();
            break;
          }
          case 50: {
            generatedcode.Flight.Builder subBuilder = null;
            if (flight_ != null) {
              subBuilder = flight_.toBuilder();
            }
            flight_ = input.readMessage(generatedcode.Flight.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(flight_);
              flight_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return generatedcode.TravelProto.internal_static_Ticket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return generatedcode.TravelProto.internal_static_Ticket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            generatedcode.Ticket.class, generatedcode.Ticket.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int CUSTOMERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object customerName_;
  /**
   * <code>string customerName = 2;</code>
   * @return The customerName.
   */
  @java.lang.Override
  public java.lang.String getCustomerName() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerName_ = s;
      return s;
    }
  }
  /**
   * <code>string customerName = 2;</code>
   * @return The bytes for customerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerNameBytes() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOURISTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object touristName_;
  /**
   * <code>string touristName = 3;</code>
   * @return The touristName.
   */
  @java.lang.Override
  public java.lang.String getTouristName() {
    java.lang.Object ref = touristName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      touristName_ = s;
      return s;
    }
  }
  /**
   * <code>string touristName = 3;</code>
   * @return The bytes for touristName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTouristNameBytes() {
    java.lang.Object ref = touristName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      touristName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMERADDRESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object customerAddress_;
  /**
   * <code>string customerAddress = 4;</code>
   * @return The customerAddress.
   */
  @java.lang.Override
  public java.lang.String getCustomerAddress() {
    java.lang.Object ref = customerAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string customerAddress = 4;</code>
   * @return The bytes for customerAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerAddressBytes() {
    java.lang.Object ref = customerAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEATS_FIELD_NUMBER = 5;
  private int seats_;
  /**
   * <code>int32 seats = 5;</code>
   * @return The seats.
   */
  @java.lang.Override
  public int getSeats() {
    return seats_;
  }

  public static final int FLIGHT_FIELD_NUMBER = 6;
  private generatedcode.Flight flight_;
  /**
   * <code>.Flight flight = 6;</code>
   * @return Whether the flight field is set.
   */
  @java.lang.Override
  public boolean hasFlight() {
    return flight_ != null;
  }
  /**
   * <code>.Flight flight = 6;</code>
   * @return The flight.
   */
  @java.lang.Override
  public generatedcode.Flight getFlight() {
    return flight_ == null ? generatedcode.Flight.getDefaultInstance() : flight_;
  }
  /**
   * <code>.Flight flight = 6;</code>
   */
  @java.lang.Override
  public generatedcode.FlightOrBuilder getFlightOrBuilder() {
    return getFlight();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, customerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(touristName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, touristName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, customerAddress_);
    }
    if (seats_ != 0) {
      output.writeInt32(5, seats_);
    }
    if (flight_ != null) {
      output.writeMessage(6, getFlight());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, customerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(touristName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, touristName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, customerAddress_);
    }
    if (seats_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, seats_);
    }
    if (flight_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getFlight());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof generatedcode.Ticket)) {
      return super.equals(obj);
    }
    generatedcode.Ticket other = (generatedcode.Ticket) obj;

    if (getId()
        != other.getId()) return false;
    if (!getCustomerName()
        .equals(other.getCustomerName())) return false;
    if (!getTouristName()
        .equals(other.getTouristName())) return false;
    if (!getCustomerAddress()
        .equals(other.getCustomerAddress())) return false;
    if (getSeats()
        != other.getSeats()) return false;
    if (hasFlight() != other.hasFlight()) return false;
    if (hasFlight()) {
      if (!getFlight()
          .equals(other.getFlight())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + CUSTOMERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerName().hashCode();
    hash = (37 * hash) + TOURISTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTouristName().hashCode();
    hash = (37 * hash) + CUSTOMERADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerAddress().hashCode();
    hash = (37 * hash) + SEATS_FIELD_NUMBER;
    hash = (53 * hash) + getSeats();
    if (hasFlight()) {
      hash = (37 * hash) + FLIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getFlight().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static generatedcode.Ticket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.Ticket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.Ticket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.Ticket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.Ticket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.Ticket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.Ticket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.Ticket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.Ticket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static generatedcode.Ticket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.Ticket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.Ticket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(generatedcode.Ticket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ticket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ticket)
      generatedcode.TicketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedcode.TravelProto.internal_static_Ticket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedcode.TravelProto.internal_static_Ticket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedcode.Ticket.class, generatedcode.Ticket.Builder.class);
    }

    // Construct using generatedcode.Ticket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      customerName_ = "";

      touristName_ = "";

      customerAddress_ = "";

      seats_ = 0;

      if (flightBuilder_ == null) {
        flight_ = null;
      } else {
        flight_ = null;
        flightBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return generatedcode.TravelProto.internal_static_Ticket_descriptor;
    }

    @java.lang.Override
    public generatedcode.Ticket getDefaultInstanceForType() {
      return generatedcode.Ticket.getDefaultInstance();
    }

    @java.lang.Override
    public generatedcode.Ticket build() {
      generatedcode.Ticket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public generatedcode.Ticket buildPartial() {
      generatedcode.Ticket result = new generatedcode.Ticket(this);
      result.id_ = id_;
      result.customerName_ = customerName_;
      result.touristName_ = touristName_;
      result.customerAddress_ = customerAddress_;
      result.seats_ = seats_;
      if (flightBuilder_ == null) {
        result.flight_ = flight_;
      } else {
        result.flight_ = flightBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof generatedcode.Ticket) {
        return mergeFrom((generatedcode.Ticket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(generatedcode.Ticket other) {
      if (other == generatedcode.Ticket.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getCustomerName().isEmpty()) {
        customerName_ = other.customerName_;
        onChanged();
      }
      if (!other.getTouristName().isEmpty()) {
        touristName_ = other.touristName_;
        onChanged();
      }
      if (!other.getCustomerAddress().isEmpty()) {
        customerAddress_ = other.customerAddress_;
        onChanged();
      }
      if (other.getSeats() != 0) {
        setSeats(other.getSeats());
      }
      if (other.hasFlight()) {
        mergeFlight(other.getFlight());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      generatedcode.Ticket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (generatedcode.Ticket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object customerName_ = "";
    /**
     * <code>string customerName = 2;</code>
     * @return The customerName.
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customerName = 2;</code>
     * @return The bytes for customerName.
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customerName = 2;</code>
     * @param value The customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customerName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerName() {
      
      customerName_ = getDefaultInstance().getCustomerName();
      onChanged();
      return this;
    }
    /**
     * <code>string customerName = 2;</code>
     * @param value The bytes for customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object touristName_ = "";
    /**
     * <code>string touristName = 3;</code>
     * @return The touristName.
     */
    public java.lang.String getTouristName() {
      java.lang.Object ref = touristName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        touristName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string touristName = 3;</code>
     * @return The bytes for touristName.
     */
    public com.google.protobuf.ByteString
        getTouristNameBytes() {
      java.lang.Object ref = touristName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        touristName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string touristName = 3;</code>
     * @param value The touristName to set.
     * @return This builder for chaining.
     */
    public Builder setTouristName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      touristName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string touristName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTouristName() {
      
      touristName_ = getDefaultInstance().getTouristName();
      onChanged();
      return this;
    }
    /**
     * <code>string touristName = 3;</code>
     * @param value The bytes for touristName to set.
     * @return This builder for chaining.
     */
    public Builder setTouristNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      touristName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customerAddress_ = "";
    /**
     * <code>string customerAddress = 4;</code>
     * @return The customerAddress.
     */
    public java.lang.String getCustomerAddress() {
      java.lang.Object ref = customerAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customerAddress = 4;</code>
     * @return The bytes for customerAddress.
     */
    public com.google.protobuf.ByteString
        getCustomerAddressBytes() {
      java.lang.Object ref = customerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customerAddress = 4;</code>
     * @param value The customerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customerAddress = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerAddress() {
      
      customerAddress_ = getDefaultInstance().getCustomerAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string customerAddress = 4;</code>
     * @param value The bytes for customerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerAddress_ = value;
      onChanged();
      return this;
    }

    private int seats_ ;
    /**
     * <code>int32 seats = 5;</code>
     * @return The seats.
     */
    @java.lang.Override
    public int getSeats() {
      return seats_;
    }
    /**
     * <code>int32 seats = 5;</code>
     * @param value The seats to set.
     * @return This builder for chaining.
     */
    public Builder setSeats(int value) {
      
      seats_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 seats = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeats() {
      
      seats_ = 0;
      onChanged();
      return this;
    }

    private generatedcode.Flight flight_;
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> flightBuilder_;
    /**
     * <code>.Flight flight = 6;</code>
     * @return Whether the flight field is set.
     */
    public boolean hasFlight() {
      return flightBuilder_ != null || flight_ != null;
    }
    /**
     * <code>.Flight flight = 6;</code>
     * @return The flight.
     */
    public generatedcode.Flight getFlight() {
      if (flightBuilder_ == null) {
        return flight_ == null ? generatedcode.Flight.getDefaultInstance() : flight_;
      } else {
        return flightBuilder_.getMessage();
      }
    }
    /**
     * <code>.Flight flight = 6;</code>
     */
    public Builder setFlight(generatedcode.Flight value) {
      if (flightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flight_ = value;
        onChanged();
      } else {
        flightBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Flight flight = 6;</code>
     */
    public Builder setFlight(
        generatedcode.Flight.Builder builderForValue) {
      if (flightBuilder_ == null) {
        flight_ = builderForValue.build();
        onChanged();
      } else {
        flightBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Flight flight = 6;</code>
     */
    public Builder mergeFlight(generatedcode.Flight value) {
      if (flightBuilder_ == null) {
        if (flight_ != null) {
          flight_ =
            generatedcode.Flight.newBuilder(flight_).mergeFrom(value).buildPartial();
        } else {
          flight_ = value;
        }
        onChanged();
      } else {
        flightBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Flight flight = 6;</code>
     */
    public Builder clearFlight() {
      if (flightBuilder_ == null) {
        flight_ = null;
        onChanged();
      } else {
        flight_ = null;
        flightBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Flight flight = 6;</code>
     */
    public generatedcode.Flight.Builder getFlightBuilder() {
      
      onChanged();
      return getFlightFieldBuilder().getBuilder();
    }
    /**
     * <code>.Flight flight = 6;</code>
     */
    public generatedcode.FlightOrBuilder getFlightOrBuilder() {
      if (flightBuilder_ != null) {
        return flightBuilder_.getMessageOrBuilder();
      } else {
        return flight_ == null ?
            generatedcode.Flight.getDefaultInstance() : flight_;
      }
    }
    /**
     * <code>.Flight flight = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> 
        getFlightFieldBuilder() {
      if (flightBuilder_ == null) {
        flightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder>(
                getFlight(),
                getParentForChildren(),
                isClean());
        flight_ = null;
      }
      return flightBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ticket)
  }

  // @@protoc_insertion_point(class_scope:Ticket)
  private static final generatedcode.Ticket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new generatedcode.Ticket();
  }

  public static generatedcode.Ticket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ticket>
      PARSER = new com.google.protobuf.AbstractParser<Ticket>() {
    @java.lang.Override
    public Ticket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Ticket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Ticket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ticket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public generatedcode.Ticket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

