// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public interface TravelMainResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelMainResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TravelMainResponse.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TravelMainResponse.Type type = 1;</code>
   * @return The type.
   */
  generatedcode.TravelMainResponse.Type getType();

  /**
   * <code>string error = 2;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  java.util.List<generatedcode.Flight> 
      getFlightsList();
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  generatedcode.Flight getFlights(int index);
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  int getFlightsCount();
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  java.util.List<? extends generatedcode.FlightOrBuilder> 
      getFlightsOrBuilderList();
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  generatedcode.FlightOrBuilder getFlightsOrBuilder(
      int index);

  /**
   * <code>.Flight flight = 4;</code>
   * @return Whether the flight field is set.
   */
  boolean hasFlight();
  /**
   * <code>.Flight flight = 4;</code>
   * @return The flight.
   */
  generatedcode.Flight getFlight();
  /**
   * <code>.Flight flight = 4;</code>
   */
  generatedcode.FlightOrBuilder getFlightOrBuilder();

  /**
   * <code>.Ticket ticket = 5;</code>
   * @return Whether the ticket field is set.
   */
  boolean hasTicket();
  /**
   * <code>.Ticket ticket = 5;</code>
   * @return The ticket.
   */
  generatedcode.Ticket getTicket();
  /**
   * <code>.Ticket ticket = 5;</code>
   */
  generatedcode.TicketOrBuilder getTicketOrBuilder();
}
