// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public interface TravelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TravelRequest.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TravelRequest.Type type = 1;</code>
   * @return The type.
   */
  generatedcode.TravelRequest.Type getType();
}
