// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public interface TravelMainRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelMainRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TravelMainRequest.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TravelMainRequest.Type type = 1;</code>
   * @return The type.
   */
  generatedcode.TravelMainRequest.Type getType();

  /**
   * <code>.Employee user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.Employee user = 2;</code>
   * @return The user.
   */
  generatedcode.Employee getUser();
  /**
   * <code>.Employee user = 2;</code>
   */
  generatedcode.EmployeeOrBuilder getUserOrBuilder();

  /**
   * <code>.Flight flight = 3;</code>
   * @return Whether the flight field is set.
   */
  boolean hasFlight();
  /**
   * <code>.Flight flight = 3;</code>
   * @return The flight.
   */
  generatedcode.Flight getFlight();
  /**
   * <code>.Flight flight = 3;</code>
   */
  generatedcode.FlightOrBuilder getFlightOrBuilder();

  /**
   * <code>.Ticket ticket = 4;</code>
   * @return Whether the ticket field is set.
   */
  boolean hasTicket();
  /**
   * <code>.Ticket ticket = 4;</code>
   * @return The ticket.
   */
  generatedcode.Ticket getTicket();
  /**
   * <code>.Ticket ticket = 4;</code>
   */
  generatedcode.TicketOrBuilder getTicketOrBuilder();

  /**
   * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
   * @return Whether the flightDestDepDTO field is set.
   */
  boolean hasFlightDestDepDTO();
  /**
   * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
   * @return The flightDestDepDTO.
   */
  generatedcode.FlightDestDepDTO getFlightDestDepDTO();
  /**
   * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
   */
  generatedcode.FlightDestDepDTOOrBuilder getFlightDestDepDTOOrBuilder();

  public generatedcode.TravelMainRequest.PayloadCase getPayloadCase();
}
