// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public final class TravelProto {
  private TravelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Flight_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Flight_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ticket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ticket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FlightDestDepDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FlightDestDepDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelMainRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelMainRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelMainResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelMainResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=TravelNetworking/src/main/java/chat/ne" +
      "twork/gRPC/travel.proto\032\037google/protobuf" +
      "/timestamp.proto\"\201\001\n\006Flight\022\n\n\002id\030\001 \001(\005\022" +
      "\023\n\013destination\030\002 \001(\t\022-\n\tdeparture\030\003 \001(\0132" +
      "\032.google.protobuf.Timestamp\022\017\n\007airport\030\004" +
      " \001(\t\022\026\n\016availableSeats\030\005 \001(\005\"\200\001\n\006Ticket\022" +
      "\n\n\002id\030\001 \001(\005\022\024\n\014customerName\030\002 \001(\t\022\023\n\013tou" +
      "ristName\030\003 \001(\t\022\027\n\017customerAddress\030\004 \001(\t\022" +
      "\r\n\005seats\030\005 \001(\005\022\027\n\006flight\030\006 \001(\0132\007.Flight\"" +
      "V\n\020FlightDestDepDTO\022\023\n\013destination\030\001 \001(\t" +
      "\022-\n\tdeparture\030\002 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\"^\n\016TravelResponse\022\"\n\004type\030\001 \001(\0162" +
      "\024.TravelResponse.Type\022\r\n\005error\030\002 \001(\t\"\031\n\004" +
      "Type\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001\"Y\n\rTravelRequest" +
      "\022!\n\004type\030\001 \001(\0162\023.TravelRequest.Type\"%\n\004T" +
      "ype\022\035\n\031FLIGHT_BY_AVAILABLE_SEATS\020\000\"\335\002\n\021T" +
      "ravelMainRequest\022%\n\004type\030\001 \001(\0162\027.TravelM" +
      "ainRequest.Type\022\031\n\004user\030\002 \001(\0132\t.Employee" +
      "H\000\022\031\n\006flight\030\003 \001(\0132\007.FlightH\000\022\031\n\006ticket\030" +
      "\004 \001(\0132\007.TicketH\000\022-\n\020flightDestDepDTO\030\005 \001" +
      "(\0132\021.FlightDestDepDTOH\000\"\225\001\n\004Type\022\t\n\005LOGI" +
      "N\020\000\022\n\n\006LOGOUT\020\001\022\025\n\021BUY_TICKET_TRAVEL\020\002\022(" +
      "\n$FLIGHTS_BY_DESTINATION_AND_DEPARTURE\020\003" +
      "\022\035\n\031FLIGHT_BY_AVAILABLE_SEATS\020\004\022\026\n\022FLIGH" +
      "T_ADD_COMPANY\020\005B\t\n\007payload\"\246\002\n\022TravelMai" +
      "nResponse\022&\n\004type\030\001 \001(\0162\030.TravelMainResp" +
      "onse.Type\022\r\n\005error\030\002 \001(\t\022\030\n\007flights\030\003 \003(" +
      "\0132\007.Flight\022\027\n\006flight\030\004 \001(\0132\007.Flight\022\027\n\006t" +
      "icket\030\005 \001(\0132\007.Ticket\"\214\001\n\004Type\022\006\n\002OK\020\000\022\t\n" +
      "\005ERROR\020\001\022\016\n\nADD_TICKET\020\002\022\016\n\nADD_FLIGHT\020\003" +
      "\022 \n\034FLIGHT_DESTINATION_DEPARTURE\020\004\022\023\n\017AV" +
      "AILABLE_SEATS\020\005\022\032\n\026ERROR_UNVAILABLE_SEAT" +
      "S\020\006\":\n\010Employee\022\n\n\002id\030\001 \001(\005\022\020\n\010username\030" +
      "\002 \001(\t\022\020\n\010password\030\003 \001(\t2\272\002\n\024ITravelServi" +
      "cesProto\022%\n\005Login\022\t.Employee\032\017.TravelRes" +
      "ponse\"\000\022&\n\006Logout\022\t.Employee\032\017.TravelRes" +
      "ponse\"\000\022H\n&FilterFlightsByDestinationAnd" +
      "Departure\022\021.FlightDestDepDTO\032\007.Flight\"\0000" +
      "\001\022;\n\034FilterFlightByAvailableSeats\022\016.Trav" +
      "elRequest\032\007.Flight\"\0000\001\022#\n\tAddTicket\022\007.Ti" +
      "cket\032\007.Ticket\"\000(\0010\001\022\'\n\tAddFlight\022\007.Fligh" +
      "t\032\017.TravelResponse\"\000B\036\n\rgeneratedcodeB\013T" +
      "ravelProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Flight_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Flight_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Flight_descriptor,
        new java.lang.String[] { "Id", "Destination", "Departure", "Airport", "AvailableSeats", });
    internal_static_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ticket_descriptor,
        new java.lang.String[] { "Id", "CustomerName", "TouristName", "CustomerAddress", "Seats", "Flight", });
    internal_static_FlightDestDepDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FlightDestDepDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FlightDestDepDTO_descriptor,
        new java.lang.String[] { "Destination", "Departure", });
    internal_static_TravelResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TravelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelResponse_descriptor,
        new java.lang.String[] { "Type", "Error", });
    internal_static_TravelRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TravelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_TravelMainRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TravelMainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelMainRequest_descriptor,
        new java.lang.String[] { "Type", "User", "Flight", "Ticket", "FlightDestDepDTO", "Payload", });
    internal_static_TravelMainResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_TravelMainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelMainResponse_descriptor,
        new java.lang.String[] { "Type", "Error", "Flights", "Flight", "Ticket", });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
