// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

/**
 * Protobuf type {@code TravelMainResponse}
 */
public final class TravelMainResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TravelMainResponse)
    TravelMainResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TravelMainResponse.newBuilder() to construct.
  private TravelMainResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TravelMainResponse() {
    type_ = 0;
    error_ = "";
    flights_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TravelMainResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TravelMainResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            error_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              flights_ = new java.util.ArrayList<generatedcode.Flight>();
              mutable_bitField0_ |= 0x00000001;
            }
            flights_.add(
                input.readMessage(generatedcode.Flight.parser(), extensionRegistry));
            break;
          }
          case 34: {
            generatedcode.Flight.Builder subBuilder = null;
            if (flight_ != null) {
              subBuilder = flight_.toBuilder();
            }
            flight_ = input.readMessage(generatedcode.Flight.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(flight_);
              flight_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            generatedcode.Ticket.Builder subBuilder = null;
            if (ticket_ != null) {
              subBuilder = ticket_.toBuilder();
            }
            ticket_ = input.readMessage(generatedcode.Ticket.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ticket_);
              ticket_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        flights_ = java.util.Collections.unmodifiableList(flights_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return generatedcode.TravelProto.internal_static_TravelMainResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return generatedcode.TravelProto.internal_static_TravelMainResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            generatedcode.TravelMainResponse.class, generatedcode.TravelMainResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code TravelMainResponse.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>ERROR = 1;</code>
     */
    ERROR(1),
    /**
     * <code>ADD_TICKET = 2;</code>
     */
    ADD_TICKET(2),
    /**
     * <code>ADD_FLIGHT = 3;</code>
     */
    ADD_FLIGHT(3),
    /**
     * <code>FLIGHT_DESTINATION_DEPARTURE = 4;</code>
     */
    FLIGHT_DESTINATION_DEPARTURE(4),
    /**
     * <code>AVAILABLE_SEATS = 5;</code>
     */
    AVAILABLE_SEATS(5),
    /**
     * <code>ERROR_UNVAILABLE_SEATS = 6;</code>
     */
    ERROR_UNVAILABLE_SEATS(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>ERROR = 1;</code>
     */
    public static final int ERROR_VALUE = 1;
    /**
     * <code>ADD_TICKET = 2;</code>
     */
    public static final int ADD_TICKET_VALUE = 2;
    /**
     * <code>ADD_FLIGHT = 3;</code>
     */
    public static final int ADD_FLIGHT_VALUE = 3;
    /**
     * <code>FLIGHT_DESTINATION_DEPARTURE = 4;</code>
     */
    public static final int FLIGHT_DESTINATION_DEPARTURE_VALUE = 4;
    /**
     * <code>AVAILABLE_SEATS = 5;</code>
     */
    public static final int AVAILABLE_SEATS_VALUE = 5;
    /**
     * <code>ERROR_UNVAILABLE_SEATS = 6;</code>
     */
    public static final int ERROR_UNVAILABLE_SEATS_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return ERROR;
        case 2: return ADD_TICKET;
        case 3: return ADD_FLIGHT;
        case 4: return FLIGHT_DESTINATION_DEPARTURE;
        case 5: return AVAILABLE_SEATS;
        case 6: return ERROR_UNVAILABLE_SEATS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return generatedcode.TravelMainResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TravelMainResponse.Type)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.TravelMainResponse.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.TravelMainResponse.Type type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public generatedcode.TravelMainResponse.Type getType() {
    @SuppressWarnings("deprecation")
    generatedcode.TravelMainResponse.Type result = generatedcode.TravelMainResponse.Type.valueOf(type_);
    return result == null ? generatedcode.TravelMainResponse.Type.UNRECOGNIZED : result;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private volatile java.lang.Object error_;
  /**
   * <code>string error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLIGHTS_FIELD_NUMBER = 3;
  private java.util.List<generatedcode.Flight> flights_;
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  @java.lang.Override
  public java.util.List<generatedcode.Flight> getFlightsList() {
    return flights_;
  }
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends generatedcode.FlightOrBuilder> 
      getFlightsOrBuilderList() {
    return flights_;
  }
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  @java.lang.Override
  public int getFlightsCount() {
    return flights_.size();
  }
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  @java.lang.Override
  public generatedcode.Flight getFlights(int index) {
    return flights_.get(index);
  }
  /**
   * <code>repeated .Flight flights = 3;</code>
   */
  @java.lang.Override
  public generatedcode.FlightOrBuilder getFlightsOrBuilder(
      int index) {
    return flights_.get(index);
  }

  public static final int FLIGHT_FIELD_NUMBER = 4;
  private generatedcode.Flight flight_;
  /**
   * <code>.Flight flight = 4;</code>
   * @return Whether the flight field is set.
   */
  @java.lang.Override
  public boolean hasFlight() {
    return flight_ != null;
  }
  /**
   * <code>.Flight flight = 4;</code>
   * @return The flight.
   */
  @java.lang.Override
  public generatedcode.Flight getFlight() {
    return flight_ == null ? generatedcode.Flight.getDefaultInstance() : flight_;
  }
  /**
   * <code>.Flight flight = 4;</code>
   */
  @java.lang.Override
  public generatedcode.FlightOrBuilder getFlightOrBuilder() {
    return getFlight();
  }

  public static final int TICKET_FIELD_NUMBER = 5;
  private generatedcode.Ticket ticket_;
  /**
   * <code>.Ticket ticket = 5;</code>
   * @return Whether the ticket field is set.
   */
  @java.lang.Override
  public boolean hasTicket() {
    return ticket_ != null;
  }
  /**
   * <code>.Ticket ticket = 5;</code>
   * @return The ticket.
   */
  @java.lang.Override
  public generatedcode.Ticket getTicket() {
    return ticket_ == null ? generatedcode.Ticket.getDefaultInstance() : ticket_;
  }
  /**
   * <code>.Ticket ticket = 5;</code>
   */
  @java.lang.Override
  public generatedcode.TicketOrBuilder getTicketOrBuilder() {
    return getTicket();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != generatedcode.TravelMainResponse.Type.OK.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, error_);
    }
    for (int i = 0; i < flights_.size(); i++) {
      output.writeMessage(3, flights_.get(i));
    }
    if (flight_ != null) {
      output.writeMessage(4, getFlight());
    }
    if (ticket_ != null) {
      output.writeMessage(5, getTicket());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != generatedcode.TravelMainResponse.Type.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, error_);
    }
    for (int i = 0; i < flights_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, flights_.get(i));
    }
    if (flight_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFlight());
    }
    if (ticket_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTicket());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof generatedcode.TravelMainResponse)) {
      return super.equals(obj);
    }
    generatedcode.TravelMainResponse other = (generatedcode.TravelMainResponse) obj;

    if (type_ != other.type_) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getFlightsList()
        .equals(other.getFlightsList())) return false;
    if (hasFlight() != other.hasFlight()) return false;
    if (hasFlight()) {
      if (!getFlight()
          .equals(other.getFlight())) return false;
    }
    if (hasTicket() != other.hasTicket()) return false;
    if (hasTicket()) {
      if (!getTicket()
          .equals(other.getTicket())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (getFlightsCount() > 0) {
      hash = (37 * hash) + FLIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getFlightsList().hashCode();
    }
    if (hasFlight()) {
      hash = (37 * hash) + FLIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getFlight().hashCode();
    }
    if (hasTicket()) {
      hash = (37 * hash) + TICKET_FIELD_NUMBER;
      hash = (53 * hash) + getTicket().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static generatedcode.TravelMainResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.TravelMainResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.TravelMainResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.TravelMainResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.TravelMainResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.TravelMainResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.TravelMainResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.TravelMainResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.TravelMainResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static generatedcode.TravelMainResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.TravelMainResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.TravelMainResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(generatedcode.TravelMainResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TravelMainResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TravelMainResponse)
      generatedcode.TravelMainResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedcode.TravelProto.internal_static_TravelMainResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedcode.TravelProto.internal_static_TravelMainResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedcode.TravelMainResponse.class, generatedcode.TravelMainResponse.Builder.class);
    }

    // Construct using generatedcode.TravelMainResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFlightsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      error_ = "";

      if (flightsBuilder_ == null) {
        flights_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        flightsBuilder_.clear();
      }
      if (flightBuilder_ == null) {
        flight_ = null;
      } else {
        flight_ = null;
        flightBuilder_ = null;
      }
      if (ticketBuilder_ == null) {
        ticket_ = null;
      } else {
        ticket_ = null;
        ticketBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return generatedcode.TravelProto.internal_static_TravelMainResponse_descriptor;
    }

    @java.lang.Override
    public generatedcode.TravelMainResponse getDefaultInstanceForType() {
      return generatedcode.TravelMainResponse.getDefaultInstance();
    }

    @java.lang.Override
    public generatedcode.TravelMainResponse build() {
      generatedcode.TravelMainResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public generatedcode.TravelMainResponse buildPartial() {
      generatedcode.TravelMainResponse result = new generatedcode.TravelMainResponse(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.error_ = error_;
      if (flightsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          flights_ = java.util.Collections.unmodifiableList(flights_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.flights_ = flights_;
      } else {
        result.flights_ = flightsBuilder_.build();
      }
      if (flightBuilder_ == null) {
        result.flight_ = flight_;
      } else {
        result.flight_ = flightBuilder_.build();
      }
      if (ticketBuilder_ == null) {
        result.ticket_ = ticket_;
      } else {
        result.ticket_ = ticketBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof generatedcode.TravelMainResponse) {
        return mergeFrom((generatedcode.TravelMainResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(generatedcode.TravelMainResponse other) {
      if (other == generatedcode.TravelMainResponse.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        onChanged();
      }
      if (flightsBuilder_ == null) {
        if (!other.flights_.isEmpty()) {
          if (flights_.isEmpty()) {
            flights_ = other.flights_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFlightsIsMutable();
            flights_.addAll(other.flights_);
          }
          onChanged();
        }
      } else {
        if (!other.flights_.isEmpty()) {
          if (flightsBuilder_.isEmpty()) {
            flightsBuilder_.dispose();
            flightsBuilder_ = null;
            flights_ = other.flights_;
            bitField0_ = (bitField0_ & ~0x00000001);
            flightsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFlightsFieldBuilder() : null;
          } else {
            flightsBuilder_.addAllMessages(other.flights_);
          }
        }
      }
      if (other.hasFlight()) {
        mergeFlight(other.getFlight());
      }
      if (other.hasTicket()) {
        mergeTicket(other.getTicket());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      generatedcode.TravelMainResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (generatedcode.TravelMainResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.TravelMainResponse.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.TravelMainResponse.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.TravelMainResponse.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public generatedcode.TravelMainResponse.Type getType() {
      @SuppressWarnings("deprecation")
      generatedcode.TravelMainResponse.Type result = generatedcode.TravelMainResponse.Type.valueOf(type_);
      return result == null ? generatedcode.TravelMainResponse.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.TravelMainResponse.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(generatedcode.TravelMainResponse.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.TravelMainResponse.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 2;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      
      error_ = getDefaultInstance().getError();
      onChanged();
      return this;
    }
    /**
     * <code>string error = 2;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      error_ = value;
      onChanged();
      return this;
    }

    private java.util.List<generatedcode.Flight> flights_ =
      java.util.Collections.emptyList();
    private void ensureFlightsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        flights_ = new java.util.ArrayList<generatedcode.Flight>(flights_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> flightsBuilder_;

    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public java.util.List<generatedcode.Flight> getFlightsList() {
      if (flightsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(flights_);
      } else {
        return flightsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public int getFlightsCount() {
      if (flightsBuilder_ == null) {
        return flights_.size();
      } else {
        return flightsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public generatedcode.Flight getFlights(int index) {
      if (flightsBuilder_ == null) {
        return flights_.get(index);
      } else {
        return flightsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder setFlights(
        int index, generatedcode.Flight value) {
      if (flightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlightsIsMutable();
        flights_.set(index, value);
        onChanged();
      } else {
        flightsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder setFlights(
        int index, generatedcode.Flight.Builder builderForValue) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.set(index, builderForValue.build());
        onChanged();
      } else {
        flightsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder addFlights(generatedcode.Flight value) {
      if (flightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlightsIsMutable();
        flights_.add(value);
        onChanged();
      } else {
        flightsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder addFlights(
        int index, generatedcode.Flight value) {
      if (flightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlightsIsMutable();
        flights_.add(index, value);
        onChanged();
      } else {
        flightsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder addFlights(
        generatedcode.Flight.Builder builderForValue) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.add(builderForValue.build());
        onChanged();
      } else {
        flightsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder addFlights(
        int index, generatedcode.Flight.Builder builderForValue) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.add(index, builderForValue.build());
        onChanged();
      } else {
        flightsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder addAllFlights(
        java.lang.Iterable<? extends generatedcode.Flight> values) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, flights_);
        onChanged();
      } else {
        flightsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder clearFlights() {
      if (flightsBuilder_ == null) {
        flights_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        flightsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public Builder removeFlights(int index) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.remove(index);
        onChanged();
      } else {
        flightsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public generatedcode.Flight.Builder getFlightsBuilder(
        int index) {
      return getFlightsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public generatedcode.FlightOrBuilder getFlightsOrBuilder(
        int index) {
      if (flightsBuilder_ == null) {
        return flights_.get(index);  } else {
        return flightsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public java.util.List<? extends generatedcode.FlightOrBuilder> 
         getFlightsOrBuilderList() {
      if (flightsBuilder_ != null) {
        return flightsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(flights_);
      }
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public generatedcode.Flight.Builder addFlightsBuilder() {
      return getFlightsFieldBuilder().addBuilder(
          generatedcode.Flight.getDefaultInstance());
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public generatedcode.Flight.Builder addFlightsBuilder(
        int index) {
      return getFlightsFieldBuilder().addBuilder(
          index, generatedcode.Flight.getDefaultInstance());
    }
    /**
     * <code>repeated .Flight flights = 3;</code>
     */
    public java.util.List<generatedcode.Flight.Builder> 
         getFlightsBuilderList() {
      return getFlightsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> 
        getFlightsFieldBuilder() {
      if (flightsBuilder_ == null) {
        flightsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder>(
                flights_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        flights_ = null;
      }
      return flightsBuilder_;
    }

    private generatedcode.Flight flight_;
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> flightBuilder_;
    /**
     * <code>.Flight flight = 4;</code>
     * @return Whether the flight field is set.
     */
    public boolean hasFlight() {
      return flightBuilder_ != null || flight_ != null;
    }
    /**
     * <code>.Flight flight = 4;</code>
     * @return The flight.
     */
    public generatedcode.Flight getFlight() {
      if (flightBuilder_ == null) {
        return flight_ == null ? generatedcode.Flight.getDefaultInstance() : flight_;
      } else {
        return flightBuilder_.getMessage();
      }
    }
    /**
     * <code>.Flight flight = 4;</code>
     */
    public Builder setFlight(generatedcode.Flight value) {
      if (flightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flight_ = value;
        onChanged();
      } else {
        flightBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Flight flight = 4;</code>
     */
    public Builder setFlight(
        generatedcode.Flight.Builder builderForValue) {
      if (flightBuilder_ == null) {
        flight_ = builderForValue.build();
        onChanged();
      } else {
        flightBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Flight flight = 4;</code>
     */
    public Builder mergeFlight(generatedcode.Flight value) {
      if (flightBuilder_ == null) {
        if (flight_ != null) {
          flight_ =
            generatedcode.Flight.newBuilder(flight_).mergeFrom(value).buildPartial();
        } else {
          flight_ = value;
        }
        onChanged();
      } else {
        flightBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Flight flight = 4;</code>
     */
    public Builder clearFlight() {
      if (flightBuilder_ == null) {
        flight_ = null;
        onChanged();
      } else {
        flight_ = null;
        flightBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Flight flight = 4;</code>
     */
    public generatedcode.Flight.Builder getFlightBuilder() {
      
      onChanged();
      return getFlightFieldBuilder().getBuilder();
    }
    /**
     * <code>.Flight flight = 4;</code>
     */
    public generatedcode.FlightOrBuilder getFlightOrBuilder() {
      if (flightBuilder_ != null) {
        return flightBuilder_.getMessageOrBuilder();
      } else {
        return flight_ == null ?
            generatedcode.Flight.getDefaultInstance() : flight_;
      }
    }
    /**
     * <code>.Flight flight = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> 
        getFlightFieldBuilder() {
      if (flightBuilder_ == null) {
        flightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder>(
                getFlight(),
                getParentForChildren(),
                isClean());
        flight_ = null;
      }
      return flightBuilder_;
    }

    private generatedcode.Ticket ticket_;
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Ticket, generatedcode.Ticket.Builder, generatedcode.TicketOrBuilder> ticketBuilder_;
    /**
     * <code>.Ticket ticket = 5;</code>
     * @return Whether the ticket field is set.
     */
    public boolean hasTicket() {
      return ticketBuilder_ != null || ticket_ != null;
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     * @return The ticket.
     */
    public generatedcode.Ticket getTicket() {
      if (ticketBuilder_ == null) {
        return ticket_ == null ? generatedcode.Ticket.getDefaultInstance() : ticket_;
      } else {
        return ticketBuilder_.getMessage();
      }
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     */
    public Builder setTicket(generatedcode.Ticket value) {
      if (ticketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ticket_ = value;
        onChanged();
      } else {
        ticketBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     */
    public Builder setTicket(
        generatedcode.Ticket.Builder builderForValue) {
      if (ticketBuilder_ == null) {
        ticket_ = builderForValue.build();
        onChanged();
      } else {
        ticketBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     */
    public Builder mergeTicket(generatedcode.Ticket value) {
      if (ticketBuilder_ == null) {
        if (ticket_ != null) {
          ticket_ =
            generatedcode.Ticket.newBuilder(ticket_).mergeFrom(value).buildPartial();
        } else {
          ticket_ = value;
        }
        onChanged();
      } else {
        ticketBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     */
    public Builder clearTicket() {
      if (ticketBuilder_ == null) {
        ticket_ = null;
        onChanged();
      } else {
        ticket_ = null;
        ticketBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     */
    public generatedcode.Ticket.Builder getTicketBuilder() {
      
      onChanged();
      return getTicketFieldBuilder().getBuilder();
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     */
    public generatedcode.TicketOrBuilder getTicketOrBuilder() {
      if (ticketBuilder_ != null) {
        return ticketBuilder_.getMessageOrBuilder();
      } else {
        return ticket_ == null ?
            generatedcode.Ticket.getDefaultInstance() : ticket_;
      }
    }
    /**
     * <code>.Ticket ticket = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Ticket, generatedcode.Ticket.Builder, generatedcode.TicketOrBuilder> 
        getTicketFieldBuilder() {
      if (ticketBuilder_ == null) {
        ticketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            generatedcode.Ticket, generatedcode.Ticket.Builder, generatedcode.TicketOrBuilder>(
                getTicket(),
                getParentForChildren(),
                isClean());
        ticket_ = null;
      }
      return ticketBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TravelMainResponse)
  }

  // @@protoc_insertion_point(class_scope:TravelMainResponse)
  private static final generatedcode.TravelMainResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new generatedcode.TravelMainResponse();
  }

  public static generatedcode.TravelMainResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TravelMainResponse>
      PARSER = new com.google.protobuf.AbstractParser<TravelMainResponse>() {
    @java.lang.Override
    public TravelMainResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TravelMainResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TravelMainResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TravelMainResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public generatedcode.TravelMainResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

