// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

public interface TravelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TravelResponse.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TravelResponse.Type type = 1;</code>
   * @return The type.
   */
  generatedcode.TravelResponse.Type getType();

  /**
   * <code>string error = 2;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
