// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelNetworking/src/main/java/chat/network/gRPC/travel.proto

package generatedcode;

/**
 * Protobuf type {@code TravelMainRequest}
 */
public final class TravelMainRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TravelMainRequest)
    TravelMainRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TravelMainRequest.newBuilder() to construct.
  private TravelMainRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TravelMainRequest() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TravelMainRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TravelMainRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            generatedcode.Employee.Builder subBuilder = null;
            if (payloadCase_ == 2) {
              subBuilder = ((generatedcode.Employee) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(generatedcode.Employee.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((generatedcode.Employee) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 2;
            break;
          }
          case 26: {
            generatedcode.Flight.Builder subBuilder = null;
            if (payloadCase_ == 3) {
              subBuilder = ((generatedcode.Flight) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(generatedcode.Flight.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((generatedcode.Flight) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 3;
            break;
          }
          case 34: {
            generatedcode.Ticket.Builder subBuilder = null;
            if (payloadCase_ == 4) {
              subBuilder = ((generatedcode.Ticket) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(generatedcode.Ticket.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((generatedcode.Ticket) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 4;
            break;
          }
          case 42: {
            generatedcode.FlightDestDepDTO.Builder subBuilder = null;
            if (payloadCase_ == 5) {
              subBuilder = ((generatedcode.FlightDestDepDTO) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(generatedcode.FlightDestDepDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((generatedcode.FlightDestDepDTO) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return generatedcode.TravelProto.internal_static_TravelMainRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return generatedcode.TravelProto.internal_static_TravelMainRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            generatedcode.TravelMainRequest.class, generatedcode.TravelMainRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code TravelMainRequest.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0),
    /**
     * <code>LOGOUT = 1;</code>
     */
    LOGOUT(1),
    /**
     * <code>BUY_TICKET_TRAVEL = 2;</code>
     */
    BUY_TICKET_TRAVEL(2),
    /**
     * <code>FLIGHTS_BY_DESTINATION_AND_DEPARTURE = 3;</code>
     */
    FLIGHTS_BY_DESTINATION_AND_DEPARTURE(3),
    /**
     * <code>FLIGHT_BY_AVAILABLE_SEATS = 4;</code>
     */
    FLIGHT_BY_AVAILABLE_SEATS(4),
    /**
     * <code>FLIGHT_ADD_COMPANY = 5;</code>
     */
    FLIGHT_ADD_COMPANY(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <code>LOGOUT = 1;</code>
     */
    public static final int LOGOUT_VALUE = 1;
    /**
     * <code>BUY_TICKET_TRAVEL = 2;</code>
     */
    public static final int BUY_TICKET_TRAVEL_VALUE = 2;
    /**
     * <code>FLIGHTS_BY_DESTINATION_AND_DEPARTURE = 3;</code>
     */
    public static final int FLIGHTS_BY_DESTINATION_AND_DEPARTURE_VALUE = 3;
    /**
     * <code>FLIGHT_BY_AVAILABLE_SEATS = 4;</code>
     */
    public static final int FLIGHT_BY_AVAILABLE_SEATS_VALUE = 4;
    /**
     * <code>FLIGHT_ADD_COMPANY = 5;</code>
     */
    public static final int FLIGHT_ADD_COMPANY_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return LOGOUT;
        case 2: return BUY_TICKET_TRAVEL;
        case 3: return FLIGHTS_BY_DESTINATION_AND_DEPARTURE;
        case 4: return FLIGHT_BY_AVAILABLE_SEATS;
        case 5: return FLIGHT_ADD_COMPANY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return generatedcode.TravelMainRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TravelMainRequest.Type)
  }

  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    USER(2),
    FLIGHT(3),
    TICKET(4),
    FLIGHTDESTDEPDTO(5),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return USER;
        case 3: return FLIGHT;
        case 4: return TICKET;
        case 5: return FLIGHTDESTDEPDTO;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.TravelMainRequest.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.TravelMainRequest.Type type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public generatedcode.TravelMainRequest.Type getType() {
    @SuppressWarnings("deprecation")
    generatedcode.TravelMainRequest.Type result = generatedcode.TravelMainRequest.Type.valueOf(type_);
    return result == null ? generatedcode.TravelMainRequest.Type.UNRECOGNIZED : result;
  }

  public static final int USER_FIELD_NUMBER = 2;
  /**
   * <code>.Employee user = 2;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.Employee user = 2;</code>
   * @return The user.
   */
  @java.lang.Override
  public generatedcode.Employee getUser() {
    if (payloadCase_ == 2) {
       return (generatedcode.Employee) payload_;
    }
    return generatedcode.Employee.getDefaultInstance();
  }
  /**
   * <code>.Employee user = 2;</code>
   */
  @java.lang.Override
  public generatedcode.EmployeeOrBuilder getUserOrBuilder() {
    if (payloadCase_ == 2) {
       return (generatedcode.Employee) payload_;
    }
    return generatedcode.Employee.getDefaultInstance();
  }

  public static final int FLIGHT_FIELD_NUMBER = 3;
  /**
   * <code>.Flight flight = 3;</code>
   * @return Whether the flight field is set.
   */
  @java.lang.Override
  public boolean hasFlight() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.Flight flight = 3;</code>
   * @return The flight.
   */
  @java.lang.Override
  public generatedcode.Flight getFlight() {
    if (payloadCase_ == 3) {
       return (generatedcode.Flight) payload_;
    }
    return generatedcode.Flight.getDefaultInstance();
  }
  /**
   * <code>.Flight flight = 3;</code>
   */
  @java.lang.Override
  public generatedcode.FlightOrBuilder getFlightOrBuilder() {
    if (payloadCase_ == 3) {
       return (generatedcode.Flight) payload_;
    }
    return generatedcode.Flight.getDefaultInstance();
  }

  public static final int TICKET_FIELD_NUMBER = 4;
  /**
   * <code>.Ticket ticket = 4;</code>
   * @return Whether the ticket field is set.
   */
  @java.lang.Override
  public boolean hasTicket() {
    return payloadCase_ == 4;
  }
  /**
   * <code>.Ticket ticket = 4;</code>
   * @return The ticket.
   */
  @java.lang.Override
  public generatedcode.Ticket getTicket() {
    if (payloadCase_ == 4) {
       return (generatedcode.Ticket) payload_;
    }
    return generatedcode.Ticket.getDefaultInstance();
  }
  /**
   * <code>.Ticket ticket = 4;</code>
   */
  @java.lang.Override
  public generatedcode.TicketOrBuilder getTicketOrBuilder() {
    if (payloadCase_ == 4) {
       return (generatedcode.Ticket) payload_;
    }
    return generatedcode.Ticket.getDefaultInstance();
  }

  public static final int FLIGHTDESTDEPDTO_FIELD_NUMBER = 5;
  /**
   * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
   * @return Whether the flightDestDepDTO field is set.
   */
  @java.lang.Override
  public boolean hasFlightDestDepDTO() {
    return payloadCase_ == 5;
  }
  /**
   * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
   * @return The flightDestDepDTO.
   */
  @java.lang.Override
  public generatedcode.FlightDestDepDTO getFlightDestDepDTO() {
    if (payloadCase_ == 5) {
       return (generatedcode.FlightDestDepDTO) payload_;
    }
    return generatedcode.FlightDestDepDTO.getDefaultInstance();
  }
  /**
   * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
   */
  @java.lang.Override
  public generatedcode.FlightDestDepDTOOrBuilder getFlightDestDepDTOOrBuilder() {
    if (payloadCase_ == 5) {
       return (generatedcode.FlightDestDepDTO) payload_;
    }
    return generatedcode.FlightDestDepDTO.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != generatedcode.TravelMainRequest.Type.LOGIN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (generatedcode.Employee) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (generatedcode.Flight) payload_);
    }
    if (payloadCase_ == 4) {
      output.writeMessage(4, (generatedcode.Ticket) payload_);
    }
    if (payloadCase_ == 5) {
      output.writeMessage(5, (generatedcode.FlightDestDepDTO) payload_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != generatedcode.TravelMainRequest.Type.LOGIN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (generatedcode.Employee) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (generatedcode.Flight) payload_);
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (generatedcode.Ticket) payload_);
    }
    if (payloadCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (generatedcode.FlightDestDepDTO) payload_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof generatedcode.TravelMainRequest)) {
      return super.equals(obj);
    }
    generatedcode.TravelMainRequest other = (generatedcode.TravelMainRequest) obj;

    if (type_ != other.type_) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 2:
        if (!getUser()
            .equals(other.getUser())) return false;
        break;
      case 3:
        if (!getFlight()
            .equals(other.getFlight())) return false;
        break;
      case 4:
        if (!getTicket()
            .equals(other.getTicket())) return false;
        break;
      case 5:
        if (!getFlightDestDepDTO()
            .equals(other.getFlightDestDepDTO())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (payloadCase_) {
      case 2:
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
        break;
      case 3:
        hash = (37 * hash) + FLIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getFlight().hashCode();
        break;
      case 4:
        hash = (37 * hash) + TICKET_FIELD_NUMBER;
        hash = (53 * hash) + getTicket().hashCode();
        break;
      case 5:
        hash = (37 * hash) + FLIGHTDESTDEPDTO_FIELD_NUMBER;
        hash = (53 * hash) + getFlightDestDepDTO().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static generatedcode.TravelMainRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.TravelMainRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.TravelMainRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.TravelMainRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.TravelMainRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static generatedcode.TravelMainRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static generatedcode.TravelMainRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.TravelMainRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.TravelMainRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static generatedcode.TravelMainRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static generatedcode.TravelMainRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static generatedcode.TravelMainRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(generatedcode.TravelMainRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TravelMainRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TravelMainRequest)
      generatedcode.TravelMainRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedcode.TravelProto.internal_static_TravelMainRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedcode.TravelProto.internal_static_TravelMainRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedcode.TravelMainRequest.class, generatedcode.TravelMainRequest.Builder.class);
    }

    // Construct using generatedcode.TravelMainRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return generatedcode.TravelProto.internal_static_TravelMainRequest_descriptor;
    }

    @java.lang.Override
    public generatedcode.TravelMainRequest getDefaultInstanceForType() {
      return generatedcode.TravelMainRequest.getDefaultInstance();
    }

    @java.lang.Override
    public generatedcode.TravelMainRequest build() {
      generatedcode.TravelMainRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public generatedcode.TravelMainRequest buildPartial() {
      generatedcode.TravelMainRequest result = new generatedcode.TravelMainRequest(this);
      result.type_ = type_;
      if (payloadCase_ == 2) {
        if (userBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = userBuilder_.build();
        }
      }
      if (payloadCase_ == 3) {
        if (flightBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = flightBuilder_.build();
        }
      }
      if (payloadCase_ == 4) {
        if (ticketBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = ticketBuilder_.build();
        }
      }
      if (payloadCase_ == 5) {
        if (flightDestDepDTOBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = flightDestDepDTOBuilder_.build();
        }
      }
      result.payloadCase_ = payloadCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof generatedcode.TravelMainRequest) {
        return mergeFrom((generatedcode.TravelMainRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(generatedcode.TravelMainRequest other) {
      if (other == generatedcode.TravelMainRequest.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getPayloadCase()) {
        case USER: {
          mergeUser(other.getUser());
          break;
        }
        case FLIGHT: {
          mergeFlight(other.getFlight());
          break;
        }
        case TICKET: {
          mergeTicket(other.getTicket());
          break;
        }
        case FLIGHTDESTDEPDTO: {
          mergeFlightDestDepDTO(other.getFlightDestDepDTO());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      generatedcode.TravelMainRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (generatedcode.TravelMainRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>.TravelMainRequest.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.TravelMainRequest.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.TravelMainRequest.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public generatedcode.TravelMainRequest.Type getType() {
      @SuppressWarnings("deprecation")
      generatedcode.TravelMainRequest.Type result = generatedcode.TravelMainRequest.Type.valueOf(type_);
      return result == null ? generatedcode.TravelMainRequest.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.TravelMainRequest.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(generatedcode.TravelMainRequest.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.TravelMainRequest.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Employee, generatedcode.Employee.Builder, generatedcode.EmployeeOrBuilder> userBuilder_;
    /**
     * <code>.Employee user = 2;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.Employee user = 2;</code>
     * @return The user.
     */
    @java.lang.Override
    public generatedcode.Employee getUser() {
      if (userBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (generatedcode.Employee) payload_;
        }
        return generatedcode.Employee.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return userBuilder_.getMessage();
        }
        return generatedcode.Employee.getDefaultInstance();
      }
    }
    /**
     * <code>.Employee user = 2;</code>
     */
    public Builder setUser(generatedcode.Employee value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.Employee user = 2;</code>
     */
    public Builder setUser(
        generatedcode.Employee.Builder builderForValue) {
      if (userBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.Employee user = 2;</code>
     */
    public Builder mergeUser(generatedcode.Employee value) {
      if (userBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != generatedcode.Employee.getDefaultInstance()) {
          payload_ = generatedcode.Employee.newBuilder((generatedcode.Employee) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          userBuilder_.mergeFrom(value);
        } else {
          userBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.Employee user = 2;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        userBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Employee user = 2;</code>
     */
    public generatedcode.Employee.Builder getUserBuilder() {
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.Employee user = 2;</code>
     */
    @java.lang.Override
    public generatedcode.EmployeeOrBuilder getUserOrBuilder() {
      if ((payloadCase_ == 2) && (userBuilder_ != null)) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (generatedcode.Employee) payload_;
        }
        return generatedcode.Employee.getDefaultInstance();
      }
    }
    /**
     * <code>.Employee user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Employee, generatedcode.Employee.Builder, generatedcode.EmployeeOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = generatedcode.Employee.getDefaultInstance();
        }
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            generatedcode.Employee, generatedcode.Employee.Builder, generatedcode.EmployeeOrBuilder>(
                (generatedcode.Employee) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();;
      return userBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> flightBuilder_;
    /**
     * <code>.Flight flight = 3;</code>
     * @return Whether the flight field is set.
     */
    @java.lang.Override
    public boolean hasFlight() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.Flight flight = 3;</code>
     * @return The flight.
     */
    @java.lang.Override
    public generatedcode.Flight getFlight() {
      if (flightBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (generatedcode.Flight) payload_;
        }
        return generatedcode.Flight.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return flightBuilder_.getMessage();
        }
        return generatedcode.Flight.getDefaultInstance();
      }
    }
    /**
     * <code>.Flight flight = 3;</code>
     */
    public Builder setFlight(generatedcode.Flight value) {
      if (flightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        flightBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.Flight flight = 3;</code>
     */
    public Builder setFlight(
        generatedcode.Flight.Builder builderForValue) {
      if (flightBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        flightBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.Flight flight = 3;</code>
     */
    public Builder mergeFlight(generatedcode.Flight value) {
      if (flightBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != generatedcode.Flight.getDefaultInstance()) {
          payload_ = generatedcode.Flight.newBuilder((generatedcode.Flight) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          flightBuilder_.mergeFrom(value);
        } else {
          flightBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.Flight flight = 3;</code>
     */
    public Builder clearFlight() {
      if (flightBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        flightBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Flight flight = 3;</code>
     */
    public generatedcode.Flight.Builder getFlightBuilder() {
      return getFlightFieldBuilder().getBuilder();
    }
    /**
     * <code>.Flight flight = 3;</code>
     */
    @java.lang.Override
    public generatedcode.FlightOrBuilder getFlightOrBuilder() {
      if ((payloadCase_ == 3) && (flightBuilder_ != null)) {
        return flightBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (generatedcode.Flight) payload_;
        }
        return generatedcode.Flight.getDefaultInstance();
      }
    }
    /**
     * <code>.Flight flight = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder> 
        getFlightFieldBuilder() {
      if (flightBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = generatedcode.Flight.getDefaultInstance();
        }
        flightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            generatedcode.Flight, generatedcode.Flight.Builder, generatedcode.FlightOrBuilder>(
                (generatedcode.Flight) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();;
      return flightBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Ticket, generatedcode.Ticket.Builder, generatedcode.TicketOrBuilder> ticketBuilder_;
    /**
     * <code>.Ticket ticket = 4;</code>
     * @return Whether the ticket field is set.
     */
    @java.lang.Override
    public boolean hasTicket() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     * @return The ticket.
     */
    @java.lang.Override
    public generatedcode.Ticket getTicket() {
      if (ticketBuilder_ == null) {
        if (payloadCase_ == 4) {
          return (generatedcode.Ticket) payload_;
        }
        return generatedcode.Ticket.getDefaultInstance();
      } else {
        if (payloadCase_ == 4) {
          return ticketBuilder_.getMessage();
        }
        return generatedcode.Ticket.getDefaultInstance();
      }
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     */
    public Builder setTicket(generatedcode.Ticket value) {
      if (ticketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        ticketBuilder_.setMessage(value);
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     */
    public Builder setTicket(
        generatedcode.Ticket.Builder builderForValue) {
      if (ticketBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        ticketBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     */
    public Builder mergeTicket(generatedcode.Ticket value) {
      if (ticketBuilder_ == null) {
        if (payloadCase_ == 4 &&
            payload_ != generatedcode.Ticket.getDefaultInstance()) {
          payload_ = generatedcode.Ticket.newBuilder((generatedcode.Ticket) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 4) {
          ticketBuilder_.mergeFrom(value);
        } else {
          ticketBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     */
    public Builder clearTicket() {
      if (ticketBuilder_ == null) {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
        }
        ticketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     */
    public generatedcode.Ticket.Builder getTicketBuilder() {
      return getTicketFieldBuilder().getBuilder();
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     */
    @java.lang.Override
    public generatedcode.TicketOrBuilder getTicketOrBuilder() {
      if ((payloadCase_ == 4) && (ticketBuilder_ != null)) {
        return ticketBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 4) {
          return (generatedcode.Ticket) payload_;
        }
        return generatedcode.Ticket.getDefaultInstance();
      }
    }
    /**
     * <code>.Ticket ticket = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.Ticket, generatedcode.Ticket.Builder, generatedcode.TicketOrBuilder> 
        getTicketFieldBuilder() {
      if (ticketBuilder_ == null) {
        if (!(payloadCase_ == 4)) {
          payload_ = generatedcode.Ticket.getDefaultInstance();
        }
        ticketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            generatedcode.Ticket, generatedcode.Ticket.Builder, generatedcode.TicketOrBuilder>(
                (generatedcode.Ticket) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 4;
      onChanged();;
      return ticketBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.FlightDestDepDTO, generatedcode.FlightDestDepDTO.Builder, generatedcode.FlightDestDepDTOOrBuilder> flightDestDepDTOBuilder_;
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     * @return Whether the flightDestDepDTO field is set.
     */
    @java.lang.Override
    public boolean hasFlightDestDepDTO() {
      return payloadCase_ == 5;
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     * @return The flightDestDepDTO.
     */
    @java.lang.Override
    public generatedcode.FlightDestDepDTO getFlightDestDepDTO() {
      if (flightDestDepDTOBuilder_ == null) {
        if (payloadCase_ == 5) {
          return (generatedcode.FlightDestDepDTO) payload_;
        }
        return generatedcode.FlightDestDepDTO.getDefaultInstance();
      } else {
        if (payloadCase_ == 5) {
          return flightDestDepDTOBuilder_.getMessage();
        }
        return generatedcode.FlightDestDepDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     */
    public Builder setFlightDestDepDTO(generatedcode.FlightDestDepDTO value) {
      if (flightDestDepDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        flightDestDepDTOBuilder_.setMessage(value);
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     */
    public Builder setFlightDestDepDTO(
        generatedcode.FlightDestDepDTO.Builder builderForValue) {
      if (flightDestDepDTOBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        flightDestDepDTOBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     */
    public Builder mergeFlightDestDepDTO(generatedcode.FlightDestDepDTO value) {
      if (flightDestDepDTOBuilder_ == null) {
        if (payloadCase_ == 5 &&
            payload_ != generatedcode.FlightDestDepDTO.getDefaultInstance()) {
          payload_ = generatedcode.FlightDestDepDTO.newBuilder((generatedcode.FlightDestDepDTO) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 5) {
          flightDestDepDTOBuilder_.mergeFrom(value);
        } else {
          flightDestDepDTOBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     */
    public Builder clearFlightDestDepDTO() {
      if (flightDestDepDTOBuilder_ == null) {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
        }
        flightDestDepDTOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     */
    public generatedcode.FlightDestDepDTO.Builder getFlightDestDepDTOBuilder() {
      return getFlightDestDepDTOFieldBuilder().getBuilder();
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     */
    @java.lang.Override
    public generatedcode.FlightDestDepDTOOrBuilder getFlightDestDepDTOOrBuilder() {
      if ((payloadCase_ == 5) && (flightDestDepDTOBuilder_ != null)) {
        return flightDestDepDTOBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 5) {
          return (generatedcode.FlightDestDepDTO) payload_;
        }
        return generatedcode.FlightDestDepDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.FlightDestDepDTO flightDestDepDTO = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        generatedcode.FlightDestDepDTO, generatedcode.FlightDestDepDTO.Builder, generatedcode.FlightDestDepDTOOrBuilder> 
        getFlightDestDepDTOFieldBuilder() {
      if (flightDestDepDTOBuilder_ == null) {
        if (!(payloadCase_ == 5)) {
          payload_ = generatedcode.FlightDestDepDTO.getDefaultInstance();
        }
        flightDestDepDTOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            generatedcode.FlightDestDepDTO, generatedcode.FlightDestDepDTO.Builder, generatedcode.FlightDestDepDTOOrBuilder>(
                (generatedcode.FlightDestDepDTO) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 5;
      onChanged();;
      return flightDestDepDTOBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TravelMainRequest)
  }

  // @@protoc_insertion_point(class_scope:TravelMainRequest)
  private static final generatedcode.TravelMainRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new generatedcode.TravelMainRequest();
  }

  public static generatedcode.TravelMainRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TravelMainRequest>
      PARSER = new com.google.protobuf.AbstractParser<TravelMainRequest>() {
    @java.lang.Override
    public TravelMainRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TravelMainRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TravelMainRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TravelMainRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public generatedcode.TravelMainRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

